name = "freemail-1"
# name = "mail-exhibit"
main = "src/server.js"
compatibility_date = "2024-01-01"

# D1 数据库绑定
[[d1_databases]]
binding = "TEMP_MAIL_DB"
database_name = "maill_free" #你的d1数据库名称
database_id = "df8669ac-cfa9-422d-8199-fcdf0399e49c" # 你的database_id
# 登录会话过期时间（单位：天，默认7天）
# 环境变量
[vars]
# FORWARD_RULES="[{"prefix":"vip","email":"a@example.com"},{"prefix":"*","email":"2141083706@qq.com"}]"


# 静态资源目录（Workers + Assets）
[assets]
directory = "public"
# 显式指定绑定名，确保在 Worker 中通过 env.ASSETS 可用
binding = "ASSETS"


# wrangler.toml (wrangler v3.88.0^) 日志服务
# [observability.logs]
# enabled = true



